{% set name = "terminaltables" %}
{% set version = "3.1.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/terminaltables-{{ version }}.tar.gz
  sha256: ba6eca5cb5ba02bba4c9f4f985af80c54ec3dccf94cfcd190154386255e47543

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}

test:
  imports:
    - terminaltables
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://robpol86.github.io/terminaltables
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Generate simple tables in terminals from a nested list of strings.
  doc_url: https://robpol86.github.io/terminaltables
  dev_url: https://github.com/Robpol86/terminaltables

extra:
  recipe-maintainers:
    - mariusvniekerk
